#ui.R for internship project

shinyUI(fluidPage(
  titlePanel("Lingual Exercise Effects on the Oropharyngeal Swallow & Dysphagia"),
  sidebarLayout(
    sidebarPanel(
#      h2("Variables"),
      selectInput("SubjID", 
                  label="Subj ID",
                  choices=list("V004","V009","V012","V020","V022","V029","V034","V036","V039","V040","V043","V044","V045","V046","V048","V049","V051","V052","V054","V059","V061","V064","V065","V066","V067","V069","V070","V075","V076","V077","V079","V081","V082","V083","V090"),
                  selected="V009"),
      
      selectInput("Time_1",
                  label="Start Point",
                  choices=list("Beginning of Posterior Movement"="BeginPosteriorMovement",
                               "Enter Head in Pharynx"="HeadEnterPharynx",
                               "Enter Tail in Pharynx"="TailEnterPharynx",
                               "Begin LVC"="BeginLVC",
                               "End LVC"="EndLVC",
                               "Beginning of Maximum Elevation"="BeginMaxElevation",
                               "First Maximum Elevation"="FirstMaxElevation",
                               "Last Maximum Elevation"="LastMaxElevation",
                               "First Maximum Anterior Movement"="FirstMaxAnterior",
                               "Last Maximum Anterior Movement"="LastMaxAnterior",
                               "Return to Rest"="ReturnToRest",
                               "CP Open"="CPOpen",
                               "Head into CP"="HeadIntoCP",
                               "Tail in CP"="TailIntoCP",
                               "CP Closed"="CPClosed"),
                  selected="Begin Posterior Movement"),
      
      selectInput("Time_2",
                  label="End Point",
                  choices=list("Beginning of Posterior Movement"="BeginPosteriorMovement",
                               "Enter Head in Pharynx"="HeadEnterPharynx",
                               "Enter Tail in Pharynx"="TailEnterPharynx",
                               "Begin LVC"="BeginLVC",
                               "End LVC"="EndLVC",
                               "Beginning of Maximum Elevation"="BeginMaxElevation",
                               "First Maximum Elevation"="FirstMaxElevation",
                               "Last Maximum Elevation"="LastMaxElevation",
                               "First Maximum Anterior Movement"="FirstMaxAnterior",
                               "Last Maximum Anterior Movement"="LastMaxAnterior",
                               "Return to Rest"="ReturnToRest",
                               "CP Open"="CPOpen",
                               "Head into CP"="HeadIntoCP",
                               "Tail in CP"="TailIntoCP",
                               "CP Closed"="CPClosed"),
                 selected="ReturnToRest"),
      sliderInput("mult",
                  label="Multiplier",
                  min=1.5,max=4.5,value=3,step=1.5)
    ),
   
    mainPanel(
      tabsetPanel(
        tabPanel("Plot",plotOutput("plot")),
        tabPanel("Baseline",tableOutput("swallowtable1")),
        tabPanel("Four-Week",tableOutput("swallowtable2")),
        tabPanel("Eight-Week",tableOutput("swallowtable3")),
        tabPanel("Operational Definitions",
                 h4(strong("ORAL")),
                 p(strong("Beginning of Posterior Movement-"),
                   "Posterior movement of the bolus head which precedes a pharyngeal response. If bolus breaks into two pieces and both are complete swallows, then take duration measures on first swallow only."),
                 p(strong("Enter Head in Pharynx-"),
                   "One frame before bolus head crosses the ramus of the mandible. if two rami are visible (i.e., head isn't lateral) use the more posterior as the landmark."),
                 p(strong("Enter Tail in Pharynx-"),
                   "Trailing edge of bolus passes ramus of mandible. If two rami are visible (i.e head isn't lateral) use the more posterior as the landmark."),
                 br(),
                 h4(strong("HYOID")),
                 p(strong("Beginning of Maximum Elevation-"),
                   "The first anterior/superior movement of the hyoid not caused by lingual pumping or jaw movement. Usually hyoid makes rapid movement and looks blurry."),
                 p(strong("First Maximum Elevation-"),
                   "The first frame representing most superior point of hyoid excursion. If hyoid reaches max more than once, use the first max."),
                 p(strong("Last Maximum Elevation-"),
                   "The last frame which reppresents most superior point of hyoid excursion."),
                 p(strong("First Maximum Anterior Movement-"),
                   "The first frame representing most anterior position of hyoid."),
                 p(strong("Last Maximum Anterior Movement-"),
                   "The last frame which represents most anterior position of hyoid."),
                 p(strong("Return to Rest-"),
                   "Hyoid may not return to starting point. Look for first frame where hyoid has stopped moving posteriorly/inferiorly and is no longer blurred. If hypoid plateaus and then drops due to tongue/jaw movement, take measure at first time of plateau."),
                 br(),
                 h4(strong("LARYNGEAL VESTIBULE")),
                 p(strong("Begin LVC-"),
                     "The first frame when contact is observed between aryntenoids and base of epiglottis."),
                 p(strong("End LVC-"),
                      "The last frame when contact is observed between aryntenoids and base of epiglottis."),
                 br(),
                 h4(strong("CRICOPHARYNGEUS")),
                    p("CP is define as the segment of the upper esophageal sphincter directly posterior to the top of the air column. Locate this segement by drawing an imaginary line from the ubercle of C1 to the anterior/posterior corner of C5 and dropping a perpendicular line to the top of the air column."),
                    p(strong("CP Open-"),
                         "Opening is indicted by a white column or lighter shade of gray at CP segment. If not, use frame where bolus enters CP (because it's obviously open then)."),
                    p(strong("Head into CP-"),
                    "Head of bolus enters CP. May be same frame as CP Open."),
                  p(strong("Tail in CP-"),
                    "Tail of bolus (greater than a wisp) at CP. Do not count residue. If bolus splits, don't include stragglers. Measure the cohesive bolus."),
                  p(strong("CP Closed-"),
                    "CP pinches closed, and there is no longer any contrast on top of sphincter. Take the screen of the first CP closure."))
      )))
    )
  )